"""
Local demo recording storage (brief §4). No real CIMET recording has been
supplied to this environment — see docs/CHECK_AUDIT.md's live-path audit.
This module generates genuine, playable WAV audio for the 9 named demo
scenarios only (never the ~300 bulk synthetic backfill leads, which are
never opened individually — see `is_seed_scenario` elsewhere in this
codebase), so the audio API and frontend player can be exercised against
real bytes instead of a simulated "playing" animation.

The audio is a low-sample-rate tone that plays at a different pitch for
AGENT vs CUSTOMER turns (silence elsewhere), generated directly from the
same turn timings the transcript was seeded from — this is SYNTHETIC DEMO
AUDIO, clearly not a real call recording, and is never presented as one
(brief §35: SYNTHETIC DEMO vs CIMET TEST ARTIFACT are architecturally
distinct). Files live under backend/data/recordings/, are regenerated by
`python -m app.seed`, and are gitignored — CLAUDE.md #9 (never commit
recordings) applies even to synthetic ones.
"""

from __future__ import annotations

import math
import wave
from pathlib import Path

RECORDINGS_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "recordings"
SAMPLE_RATE = 4000
AGENT_FREQ_HZ = 440.0
CUSTOMER_FREQ_HZ = 660.0
AMPLITUDE = 40  # quiet tone; 8-bit unsigned PCM centered at 128


def recording_path(lead_id: str) -> Path:
    return RECORDINGS_DIR / f"{lead_id}.wav"


def has_recording(lead_id: str) -> bool:
    return recording_path(lead_id).is_file()


def generate_demo_recording(lead_id: str, duration_seconds: int, turns: list) -> Path:
    """`turns` items must expose `.speaker`, `.start`, `.end_seconds` (the
    same seed_data.py turn objects create_transcript() consumes) so the
    audible tone lines up with the real seeded transcript segments."""
    RECORDINGS_DIR.mkdir(parents=True, exist_ok=True)
    path = recording_path(lead_id)

    n_samples = max(1, int(duration_seconds * SAMPLE_RATE))
    samples = bytearray(b"\x80" * n_samples)  # silence baseline

    for turn in turns:
        freq = AGENT_FREQ_HZ if turn.speaker == "AGENT" else CUSTOMER_FREQ_HZ
        s0 = max(0, int(turn.start * SAMPLE_RATE))
        s1 = min(n_samples, int(turn.end_seconds * SAMPLE_RATE))
        for i in range(s0, s1):
            t = i / SAMPLE_RATE
            samples[i] = 128 + int(AMPLITUDE * math.sin(2 * math.pi * freq * t))

    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(1)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(bytes(samples))

    return path
